### ISSUE TITLE
Proj 1 skeleton

### ISSUE THREAD

**Issue by bfdes** [berkeley-cs186/fa20-moocbase#1]
I'm following CS186 [2018 lectures on YouTube](https://www.youtube.com/channel/UCG50NrblEgrTaNssZ0EIDog) and trying to complete the tasks on the CS186 [2020 website](https://cs186.gitbook.io/project/) as they appear. 

I understand this is a public copy of the GitHub Classroom repos Berkeley students use. I would like to know whether it will be updated with the other skeletons, as they become available. 

Obviously, since I'm not a Berkeley student, I don't expect to be able to submit work or use the forums!

**Comment by ckw017** [comment]
Yeah, this is what GitHub classroom will actually be distributing copies of this throughout the semester so its the exact same, and will get updated as we make changes. Project 1 will actually be off of a different repo (fa20-proj1), but that's also exactly the same as what berkeley students will be getting.

**Comment by bfdes** [comment]
Great, thank you! I appreciate the fact that material is being open-sourced.
